# -*- coding: utf-8 -*-
"""Bdd_app_build.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SR9a5po4GCVsqx909RC6hcOzwnc_TRMX
"""

import streamlit as st
import google.generativeai as genai
import yfinance as yf
import pandas as pd
import plotly.graph_objects as go
import plotly.express as px
import json
import re
from fpdf import FPDF
import base64
from docx import Document
import io


# --- ページ設定 ---
st.set_page_config(page_title="Quick BDD Analyzer", layout="wide")
st.title("📈 Quick Business Due Diligence Analyzer")

# --- サイドバー：APIキー設定 ---
with st.sidebar:
    st.header("Settings")
    api_key = st.text_input("Enter Gemini API Key", type="password")
    if api_key:
        genai.configure(api_key=api_key)
        # 最新モデルを自動取得
        try:
            available_models = [m.name for m in genai.list_models() if 'generateContent' in m.supported_generation_methods]
            selected_model = next((m for m in available_models if 'flash' in m), available_models[0])
            st.success(f"Model Active: {selected_model}")
        except:
            selected_model = "gemini-1.5-flash" # フォールバック

# --- PDF生成クラス ---
class BDD_PDF(FPDF):
    def header(self):
        self.set_font('Helvetica', 'B', 15)
        self.cell(0, 10, 'Strategic BDD Report', 0, 1, 'C')
        self.ln(10)

# --- Word生成用の関数 ---
def create_word(target, description, report_text):
    doc = Document()
    doc.add_heading('Strategic BDD Report', 0)
    doc.add_heading(f'Target Analysis: {target}', level=1)
    doc.add_paragraph(f"Description: {description}")
    doc.add_heading('Analysis Results', level=1)
    doc.add_paragraph(report_text)
    
    bio = io.BytesIO()
    doc.save(bio)
    return bio.getvalue()        

def create_pdf(target, description, report_text):
    pdf = BDD_PDF()
    pdf.add_page()
    pdf.set_font("Helvetica", size=12)
    pdf.cell(0, 10, f"Target Analysis: {target}", ln=True)
    pdf.ln(5)
    pdf.multi_cell(0, 10, f"Description: {description}")
    pdf.ln(10)
    pdf.multi_cell(0, 10, report_text.encode('latin-1', 'replace').decode('latin-1'))
    return pdf.output()

# --- メインロジック ---
target_name = st.text_input("分析対象を入力（例：岐阜タンメン）", "")

if st.button("Deep Analysis 開始"):
    if not api_key:
        st.error("APIキーを入力してください")
    elif target_name:
        model = genai.GenerativeModel(selected_model)

        # 1. 競合特定
        with st.spinner("🔍 AIが市場構造を調査中..."):
            comp_prompt = f"「{target_name}」のBDDを行います。事業概要と上場競合5社の銘柄コード(.T)をJSON形式のみで出力： {{'description': '...', 'competitors': [{{'name': '...', 'ticker': '...'}}]}}"
            res = model.generate_content(comp_prompt)
            data = json.loads(re.search(r'\{.*\}', res.text, re.DOTALL).group())
            st.subheader(f"✅ 対象企業の定義: {target_name}")
            st.info(data['description'])

        # 2. 財務データ取得
        with st.spinner("📡 財務データを抽出中..."):
            summary_results = []
            for comp in data['competitors']:
                try:
                    stock = yf.Ticker(comp['ticker'])
                    info = stock.info
                    summary_results.append({
                        "企業名": comp['name'],
                        "時価総額(億)": round(info.get('marketCap', 0) / 1e8, 1),
                        "売上高(億)": round(info.get('totalRevenue', 0) / 1e8, 1),
                        "営業利益率(%)": round(info.get('operatingMargins', 0) * 100, 1),
                        "ROE(%)": round(info.get('returnOnEquity', 0) * 100, 1)
                    })
                except: continue
            df = pd.DataFrame(summary_results)
            st.dataframe(df.style.format(precision=1).background_gradient(cmap='Blues'))

        # 3. ビジュアル化
        fig = px.scatter(df, x="営業利益率(%)", y="ROE(%)", size="時価総額(億)", color="企業名", text="企業名", template="plotly_white")
        st.plotly_chart(fig, use_container_width=True)

        # 4. BDDレポート生成
        with st.spinner("📝 戦略コンサル視点での提言を生成中..."):
            table_str = df.to_markdown()
            report_prompt = f"""
    あなたはゴールドマンサックス（IB）のシニアアナリストです。
    以下の最新財務比較データに基づき、「{target_name}」に関連する市場環境と競合他社の分析レポートを作成してください。

    【比較対象データ】
    {table_str}

    【レポート構成】
    1. エグゼクティブ・サマリー：
       業界全体のファンダメンタルズ/競合優位性/ {target_name}の現状および強みを踏まえた成長戦略。
       1-1.事業戦略
       1-2.人事戦略
       1-3.財務戦略
    2. 市場構造と成長ドライバー（Market Dynamics）:
       2-1.業界のKFS（重要成功要因）と、現在および将来のマクロ環境が与えるインパクト。
       2-2.足元成長を後押ししているトレンド/成長率の高いセグメント（顧客層/価格帯など）
       2-3.マルチプル（PER等）の観点から見た、業界のバリュエーション水準。
    3. 稼ぐ力と資本効率の定量的比較：
       3-1.営業利益率とROEの相関から見る、競合各社の「参入障壁」と「経営効率」の差を生む構造的要因（コスト構造、アセットライトモデル等）の解剖
       3-2.競合各社の財務数値から透けて見える「各社の勝ちパターン/強み」の特定
    4. {target_name}（非上場）への戦略的提言：
       4-1.マーケットと競合、  {target_name}の公開データから取りうる戦略オプションの洗い出し
       4-2.数年で2-3倍の収益を目指す目線での仮評価
       　　現状のバリュエーション水準に基づき、どのようなレバー（出店加速、単価アップ等）を引けば企業価値が最大化するか。
    5. 事業推進上の致命的リスク（Red Flags）:
       BDDの観点から、将来の成長を阻害する可能性のある構造的リスク。

    ※プロフェッショナルな論調で、投資委員会に提出するレベルの具体的数値に基づいた示唆を出してください。
    """
           with st.spinner("📝 戦略レポートを生成中..."):
            # ...（レポート生成ロジックはそのまま）...
            report = model.generate_content(report_prompt)
            report_content = report.text
            
            st.markdown("---")
            st.markdown("## 📘 Strategic BDD Report")
            st.markdown(report_content)

            # --- 出力選択セクション ---
            st.subheader("📥 レポートをダウンロード")
            col_pdf, col_word = st.columns(2)

            with col_pdf:
                try:
                    pdf_data = create_pdf(target_name, data['description'], report_content)
                    st.download_button(
                        label="📄 PDF形式で保存",
                        data=pdf_data,
                        file_name=f"BDD_Report_{target_name}.pdf",
                        mime="application/pdf"
                    )
                except:
                    st.error("PDF生成に失敗しました")

            with col_word:
                word_data = create_word(target_name, data['description'], report_content)
                st.download_button(
                    label="📝 Word形式で保存",
                    data=word_data,
                    file_name=f"BDD_Report_{target_name}.docx",
                    mime="application/vnd.openxmlformats-officedocument.wordprocessingml.document"
                )
